# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevice', '0002_devicestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicestatus',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='channel',
            field=models.CharField(default='ht', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='status',
            field=jsonfield.fields.JSONField(),
        ),
    ]
